#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# keyboard layout for x11
[ "$XDG_SESSION_TYPE" != wayland ] && setxkbmap fr -option caps:escape

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[bash] \W$ '

# common aliases
alias vim=nvim
alias py=python3
alias l="ls -Al"
alias icat="kitten icat" # kitty
alias mnt="sudo mount -o uid=1000,gid=1000,umask=022"
function mkcd() {
    mkdir -p "$@"
    cd "$1"
}
alias sd0="shutdown 0"

EDITOR=vim

# c EPITA
function mk() {
    gcc -o "$1" **.c -Wall -Wextra -Wvla -Werror -pedantic -std=c99 -fsanitize=address -g -lcriterion
    if [ $? = 0 ]; then
        file="$1"
        shift
        "./$file" "$@"
        echo "Exit status: $?"
    fi
}

color()(set -o pipefail;"$@" 2>&1>&3|sed $'s,.*,\e[31m&\e[m,'>&2)3>&1

# other utils
eval "$(zoxide init posix --hook prompt)"
alias ls=eza
alias cd=z
alias rm="rm -I"
alias 223="echo '   223'"

alias fix-opera='sudo ~root/.scripts/fix-opera.sh' # Opera fix HTML5 media

# git
alias gs="git status"
alias gd="git diff"
alias ga="git add --all"
alias gc="git commit -m "
alias gac="ga ; gc"
alias gcm="git commit --amend"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gf="git pull"
alias gl="git log --oneline"
alias grl="git reflog"
alias gg="git log --graph --oneline --decorate --all"

export PATH="$HOME/.local/bin:$PATH"

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
