#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "NixOS (Submenu)" {
    insmod part_gpt
    insmod fat
    search --no-floppy --fs-uuid --set=root 1D0C-E2E5
    chainloader /EFI/NixOS-boot/grubx64.efi
}
