" ~/.vimrc

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'joshdick/onedark.vim'

call vundle#end()

filetype plugin indent on
syntax on
set encoding=utf-8 fileencodings=
autocmd Filetype make setlocal noexpandtab
set list listchars=tab:»·,trail:█

set number
set relativenumber
set cc=80
set expandtab
set shiftwidth=4
set tabstop=4
set smartindent
set ignorecase
set smartcase
set incsearch
set undofile
set autowrite
set autoread
set termguicolors

nnoremap <C-l> :clang-format -i %<Cr>

colorscheme onedark

packadd termdebug
let g:termdebug_wide=1
